#ライブラリのインポート


In [2]:
#ライブラリのインポート
import numpy as np

print('numpyのバージョンは:',np.__version__)

numpyのバージョンは: 1.22.4


#定義

In [3]:
a=np.array([1,2,3])
print('a=',a)
#要素数確認
print(a.shape)

print(len(a))

a= [1 2 3]
(3,)
3


#配列の演算

In [4]:
#かけ算
a*3

array([3, 6, 9])

In [5]:
#足し算
a+2

array([3, 4, 5])

In [6]:
b=np.array([1,1,4])
print('b=',b)

b= [1 1 4]


In [7]:
a+b

array([2, 3, 7])

In [8]:
a-b

array([ 0,  1, -1])

In [9]:
a/b

array([1.  , 2.  , 0.75])

In [10]:
a*b

array([ 1,  2, 12])

##ベクトルの内積

In [11]:
np.dot(a,b)

15

In [12]:
c=np.array([[1,2],[3,4]])
print('c=',c)
d=np.array([[3,4],[1,2]])
print('d=',d)

c= [[1 2]
 [3 4]]
d= [[3 4]
 [1 2]]


In [13]:
np.dot(c,d)

array([[ 5,  8],
       [13, 20]])

In [14]:
e=np.array([[1,2,3],[3,4,5],[6,7,8]])
print('e=',e)
f=np.array([[6,7,8],[3,4,5],[1,2,3]])
print('f=',f)

e= [[1 2 3]
 [3 4 5]
 [6 7 8]]
f= [[6 7 8]
 [3 4 5]
 [1 2 3]]


In [15]:
np.dot(e,f)

array([[ 15,  21,  27],
       [ 35,  47,  59],
       [ 65,  86, 107]])

##配列の形状変換

In [16]:
g=np.arange(9).reshape((3,3))
print('g=',g)

g= [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
g=g.reshape((1,-1))
print(g)

[[0 1 2 3 4 5 6 7 8]]


In [18]:
#要素がゼロの配列
zeros=np.zeros((3,4))
print('zeros=',zeros)

zeros= [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
#要素が1の配列
h=np.ones((3,3))
print('h=',h)

h= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
#未初期化の配列の生成
p=np.empty((2,3))
print('p=',p)

p= [[1.991079e-316 0.000000e+000 0.000000e+000]
 [0.000000e+000 0.000000e+000 0.000000e+000]]


In [21]:
#matrixで2次元配列の作成
k=np.matrix([[0,1,2],[3,4,5],[6,7,8]])
print('k=',k)

k= [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
l=np.matrix([[1,1,1],[1,1,1],[1,1,1]])
print('l=',l)

m=np.dot(k,l)
print('m=',m)
print(m.shape)

l= [[1 1 1]
 [1 1 1]
 [1 1 1]]
m= [[ 3  3  3]
 [12 12 12]
 [21 21 21]]
(3, 3)


#arangeで配列生成

In [23]:
n=np.arange(100).reshape(10,10)
print('n=',n)

n= [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [24]:
o=np.arange(start=100,stop=600,step=100)
print(o)

[100 200 300 400 500]


In [25]:
p=np.arange(10)
print(p)

[0 1 2 3 4 5 6 7 8 9]
